### ISSUE TITLE
Mention/Ping Toggle

### ISSUE THREAD

**Issue by Jaimss** [HelpChat/ChatChat#108]
Instead of a one size fits all `.block` permission that blocks no matter what, a command to toggle pings or toggle mentions would be good.

This command would require the `.block` permission, and then you would not check if they have permission, but if they want to block pings.

I'll PR this if it is received positively

**Comment by BlitzOffline** [comment]
That's definitely something I've considered before. Its not a bad idea. This is one extra reason for adding storage. We need to store all this information so they won't have to toggle every time. I feel like that's an issue that should have priority. We can definitely implement this one tho.

**Comment by Jaimss** [comment]
It took like 2 minutes to implement with the current system, so I'll open a PR and just modify it once the storage system is implemented
