### ISSUE TITLE
Change to Social Spy event Priority REQUEST

### ISSUE THREAD

**Issue by spookymgmt** [HelpChat/ChatChat#114]
https://img001.prntscr.com/file/img001/w4OIokX0QP6FAorpDYXhgg.png

As seen in the image above, if you /msg or /r to someone, it'll sometimes show the socialspy message last, rather than first. Social spy should always be the first one to send.

**Comment by BlitzOffline** [comment]
This can be easily changed by switching from using a Map here, to a LinkedHashMap so it keeps its order. We will be making this change after PR #116 will be merged to avoid unnecessary conflicts.

https://github.com/HelpChat/ChatChat/blob/4941d6083583674758d6c33c8c463fdd711ac5e0/plugin/src/main/java/at/helpch/chatchat/command/WhisperCommand.java#L92-L103

**Comment by BlitzOffline** [comment]
> [img001.prntscr.com/file/img001/w4OIokX0QP6FAorpDYXhgg.png](https://img001.prntscr.com/file/img001/w4OIokX0QP6FAorpDYXhgg.png)
> 
> As seen in the image above, if you /msg or /r to someone, it'll sometimes show the socialspy message last, rather than first. Social spy should always be the first one to send.

I've somehow only now realized that you want the socialspy message to show first. Why would you want this? It makes no sense. If the message wasn't send yet what would you actually spy on. I'm not going to make it this way, and socialspy will stay last but I'm fixing it so it will be consistent and always last.
