### ISSUE TITLE
Chatcolor Suggestion

### ISSUE THREAD

**Issue by LagClear** [HelpChat/ChatChat#12]
Allowing permission based chat color as well as supporting gradient.

Permission Example:
chatchat.chatcolor.32221
chatchat.chatcolor.33332_11111

This will allow more customization options for server owners as well as removing another needed plugin for changing chat colors quickly.

**Comment by LagClear** [comment]
This would override the default format one thats set in the config

**Comment by BlitzOffline** [comment]
Same thing as I said in #13 we should let other plugins that have placeholders to handle it or make our own separate plugin for both name and chat colors and have it return the correct color format with placeholders. But this shouldn't be something we prioritise.
