### ISSUE TITLE
Message overrides in messages.yml not respected

### ISSUE THREAD

**Issue by notjoshmiles** [HelpChat/ChatChat#127]
Hi,

Just noticed that any changes in messages.yml aren't reflected when the plugin is in use. I'm assuming that's because they've been defined in https://github.com/HelpChat/ChatChat/blob/main/plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java and aren't using the ones from the config instead.

Expected outcome: changes in messages.yml should work

**Comment by BlitzOffline** [comment]
> Hi,
> 
> Just noticed that any changes in messages.yml aren't reflected when the plugin is in use. I'm assuming that's because they've been defined in [https://github.com/HelpChat/ChatChat/blob/main/plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java](https://github.com/HelpChat/ChatChat/blob/main/plugin/src/main/java/at/helpch/chatchat/config/holders/MessagesHolder.java?rgh-link-date=2022-08-13T21%3A20%3A59Z) and aren't using the ones from the config instead.
> 
> Expected outcome: changes in messages.yml should work

The messages require a `/chatchat reload` to refresh as we're caching them. I'm pretty sure they do work as I've just recently tested something about this.

**Comment by notjoshmiles** [comment]
@BlitzOffline - I've tried both that and a full server restart and they don't seem to be updating

**Comment by BlitzOffline** [comment]
> @BlitzOffline - I've tried both that and a full server restart and they don't seem to be updating

That's very strange. I just tested with build 27 from jenkins. 
![image](https://user-images.githubusercontent.com/52609756/184511227-cd722f42-414c-4a26-843c-6ebe80efc961.png)

**Comment by notjoshmiles** [comment]
I'm running build 21, let's see if 27 fixes anything

**Comment by notjoshmiles** [comment]
Latest build seemed to fix it - thanks @BlitzOffline
