### ISSUE TITLE
[Suggestion] Make the expiration time for lastMessageUser configurable. 

### ISSUE THREAD

**Issue by joeyahines** [HelpChat/ChatChat#129]
Currently, the plugin has this hardcoded to 5 minutes [here](https://github.com/HelpChat/ChatChat/blob/main/plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java#L27). I think this would be good to make this timeout configurable (or possibly disable it all together). 

I wouldn't mind taking a stab at this if this sounds like something other would want.

P.S. I just wanted to say ChatChat has been working really well overall on our medium sized survival server. We had been using DC for years and switched for our recent reset.

**Comment by darbyjack** [comment]
I wouldn't mind it being configurable. If you want to take a stab at it, go ahead.

**Comment by BlitzOffline** [comment]
> Currently, the plugin has this hardcoded to 5 minutes [here](https://github.com/HelpChat/ChatChat/blob/main/plugin/src/main/java/at/helpch/chatchat/user/ChatUserImpl.java?rgh-link-date=2022-08-14T01%3A32%3A20Z#L27). I think this would be good to make this timeout configurable (or possibly disable it all together).
> 
> I wouldn't mind taking a stab at this if this sounds like something other would want.
> 
> P.S. I just wanted to say ChatChat has been working really well overall on our medium sized survival server. We had been using DC for years and switched for our recent reset.

just let me know if you want to do it or if you already started doing it, otherwise I can do it today.
