### ISSUE TITLE
Namecolor Suggestion

### ISSUE THREAD

**Issue by LagClear** [HelpChat/ChatChat#13]
A permission based name color option allowing more customizations and supporting gradient.

Permission example:
chatchat.namecolor.11111
chatchat.namecolor.13332_11231

**Comment by LagClear** [comment]
This would override the default format one thats set in the config

**Comment by BlitzOffline** [comment]
The thing is we don't have a "name color". The format is literally just strings we concatenate. See here: https://github.com/HelpChat/ChatChat/blob/2e756cf4698b5c44b86b22446d74cef2a6db705f/plugin/src/main/resources/formats.yml#L5

I really think we should let this to other plugins that could just provide a placeholder instead. Or maybe if we end up making our own ChatChatColor plugin and just have it do both this and names with placeholders. That way we can make sure the placeholders return the correct format for ChatChat aka the minimessages format aka <#aaFF00>.
