### ISSUE TITLE
/ignore, only ignores messages from the public chat and not private messages

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/ChatChat#132]
When a user ignores another user, they will still be able to send and receive private messages to and from that user. This seems like an oversight.

I personally believe that if you ignore a user:

- that user can't DM you,
- you can't DM that user,
- you won't see public messages from that user
- they will still see those public messages from you.

**Comment by Jaimss** [comment]
Yep, I forgot about PMs when I added the ignore command. I can take this if you want.
