### ISSUE TITLE
Format tags ignore permission checks

### ISSUE THREAD

**Issue by joeyahines** [HelpChat/ChatChat#136]
It appears that format tags are not respecting permissions associated to that tag.

Test with `chathcat.tag.color`
![Screenshot_20220820_114856](https://user-images.githubusercontent.com/7283070/185760303-1d5f1f10-6c85-4b5e-910e-d5537f6774ce.png)

Test with `chathcat.tag.bold`
![image](https://user-images.githubusercontent.com/7283070/185760327-55d022f1-bad2-4d61-880c-f8875eaa7a8d.png)

While debugging it looks like the permission checks are building the resolver correctly, but Minimessage renders the tags anyway.

**Comment by BlitzOffline** [comment]
Interesting. Will look into it right away.

**Comment by BlitzOffline** [comment]
Found the problem. We're not using a custom MiniMessage instance but rather the default one.

https://github.com/HelpChat/ChatChat/blob/76e449732f1629e8f43f8b32eb2c7c70631ba2fe/plugin/src/main/java/at/helpch/chatchat/util/MessageProcessor.java#L346-L347

Will make a PR with the fix soon.
