### ISSUE TITLE
ChatChat doesn't send message when player lacks perms to see default channels

### ISSUE THREAD

**Issue by Andre601** [HelpChat/ChatChat#160]
When you don't explicitly grant `chatchat.channel.see.<default_channel_name>` for the normal player to see the default channel is ChatChat treating it as if the player isn't allowed to see it, resulting in their messages not being displayed in chat, but still logged in console.

ChatChat should actually treat no see permissions as using the default channel without any permission checks.

**Comment by BlitzOffline** [comment]
I am pretty sure I've actually fixed this in a PR. I Just don't remember which. I will be testing again this week just to make sure.

**Comment by BlitzOffline** [comment]
Closed. Retested just to make sure and it seems to be fixed.
