### ISSUE TITLE
ItemsAdder plugin compatibility

### ISSUE THREAD

**Issue by ColorsASD** [HelpChat/ChatChat#172]
After I stop the server I get the following error:

Exception: java.lang.NoClassDefFoundError thrown from the UncaughtExceptionHandler in thread "Server thread"

Versions:
- ItemsAdder: v3.2.4-beta1
- ChatChat: v1.0-b47
- Purpur: git-Purpur-1428 (MC: 1.17.1)
- Java: Eclipse Temurin JDK with Hotspot 17.0.3+7 (x64)

**Comment by BlitzOffline** [comment]
Is that the entire error? There should probably be more. Send it all please.

**Comment by ColorsASD** [comment]
It will not be a plugin error, but the error comes from java, so there is no log for me.

And this error is caused by the two plugins.
(If we get rid of one, everything works perfectly. But I'm definitely not going to delete ItemsAdder.)

Log:
![image](https://user-images.githubusercontent.com/12263156/198873183-c55abea7-5a97-41fd-ba4a-120d1ab956a7.png)

Console:
![image](https://user-images.githubusercontent.com/12263156/198873205-f0f218f4-18b1-445d-8b92-4af6e7a66f62.png)

Everything is just plain frozen.
I can only see the pictures, there is no big error log in the main directory of the server.

**Comment by Kqliber** [comment]
closing this as the error mentioned was fixed in #173
