### ISSUE TITLE
No tab completion for command arguments

### ISSUE THREAD

**Issue by BlitzOffline** [HelpChat/ChatChat#179]
Seems like tab completion for arguments doesn't work right now. Tested with `/msg <player-name>` and `/ignore <player-name>`.

Matt has confirmed that triumph-cmds has some issues with suggestions at this time but I have not confirmed yet that those are the same issues.

**Comment by smuddgge** [comment]
The server I work on is having the same issue, we have had to go back to `Version 41`

**Comment by BlitzOffline** [comment]
This was fixed by Matt and a jenkins build with the latest snapshot of the command library was published: https://ci.extendedclip.com/job/ChatChat/51/
