### ISSUE TITLE
Please support API2D

### ISSUE THREAD

**Issue by itsdrchen** [HelpChat/ChatChat#206]
i love your work! please suppor API2D https://api2d.com/wiki/doc, a third-party ChatGPT service, API HOST is https://openai.api2d.net/.
Thanks for your hard working!

**Comment by BlitzOffline** [comment]
This isn't a feature that's really meant for ChatChat. It sounds rather like something a completely separate plugin would do. ChatChat has a nice API tho so it could be made to work with ChatChat tho. We are not going to make that plugin however.
