### ISSUE TITLE
Found out an issue when using build server (or really when just attempting to compile myself)

### ISSUE THREAD

**Issue by Gyztor** [HelpChat/ChatChat#21]
when attempting to build gave this error:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine the dependencies of task ":api:javadoc".
> Could not resolve all dependencies for configuration ":api:compileClasspath".
  The project declares repositories, effectively ignoring the repositories you have declared in the settings.
  You can figure out how project repositories are declared by configuring your build to fail on project repositories.
  See https://docs.gradle.org/7.4.1/userguide/declaring_repositories.html#sub:fail_build_on_project_repositories for details.
   > Could not find org.spigotmc:spigot-api:1.18.1-R0.1-SNAPSHOT.
     Searched in the following locations:
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/maven-metadata.xml
       - https://repo.maven.apache.org/maven2/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/spigot-api-1.18.1-R0.1-SNAPSHOT.pom
       - file:/root/.m2/repository/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/maven-metadata.xml
       - file:/root/.m2/repository/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/spigot-api-1.18.1-R0.1-SNAPSHOT.pom
     Required by:
         project :api

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Get more help at https://help.gradle.org/

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use "--warning-mode all" to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.4.1/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 6s
10 actionable tasks: 10 up-to-date
Build step "Invoke Gradle script" changed build result to FAILURE
Build step "Invoke Gradle script" marked build as failure
[Checks API] No suitable checks publisher found.
Finished: FAILURE

did some digging and found that in ChatChat/build-logic/src/main/kotlin/chatchat.base-conventions.gradle.kts
changing
`repositories {
    mavenCentral()
    mavenLocal()
}`
to
`repositories {
    maven("https://hub.spigotmc.org/nexus/content/repositories/snapshots/")
    maven("https://repo.maven.apache.org/maven2")
}`
fixes it and allows the build to succeed. the 2nd repo is the same on as mavenCentral() so it should still be pulling from the same place.
sorry for bad format as i havent done github formatting in awhile and am a bit too lazy to try and fix it unless someone has issues understanding it.

**Comment by Gyztor** [comment]
this change should also remove the need to have the spigotmc snapshots local

**Comment by Starmism** [comment]
How are you building it? I just recently fresh-built it by running `./gradlew shadowJar`, no local dependencies required. It should just pull everything from Maven repositories.

**Comment by Gyztor** [comment]
nope just using your repo and doing `./gradlew shadowJar` gives an error as it cant find the spigot stuff in `https://repo.maven.apache.org/maven2/org/spigotmc/spigot-api/1.18.1-R0.1-SNAPSHOT/...`

**Comment by Gyztor** [comment]
works with shadowJar with my configuration (Pulling from Gyztor/HelpChat) but not with the original (Pulling from HelpChat/ChatChat). the only issue is with mine it doesnt include the actual plugin but it does at least build which is kinda funny but i think somehow the github may somehow not have something or when building something isnt being included somehow. (if your curios what it does give: [https://jenkins.havensedgemc.com/job/ChatChat/lastSuccessfulBuild/artifact/build/libs/chat-chat-1.0.jar](https://jenkins.havensedgemc.com/job/ChatChat/lastSuccessfulBuild/artifact/build/libs/chat-chat-1.0.jar))

**Comment by Kqliber** [comment]
so the issue was that the api module didn't have a repo to find the spigot api, so it tried to find it in mavenLocal, and conveniently, everyone who has built the project so far has had the spigot api in their mavenLocal hence why we could all build the project. This issue is fixed with #22

**Comment by Gyztor** [comment]
alright let me give a direct pull a shot and see what happens.

**Comment by Gyztor** [comment]
okay that build has worked with no issues the only issue i have run into so far is that the plugin includes literally nothing but META-INF/MANIFEST.MF. but the build is working with your changes. Though i am still using `gradlew build` which has been the thing actually building anything as `gradlew shadowJar` as recommended by @Starmism has not worked for me so far.

**Comment by Kqliber** [comment]
u will need to grab the jar from plugin/build/libs for the actual plugin. And you will need to run shadowJar so that the dependencies are bundled in the plugin. without the dependencies, the plugin won't load correctly.
if you only want the plugin jar, u can run `gradlew :plugin:shadowJar`

**Comment by Gyztor** [comment]
thank you for the info on the location. i feel kinda dumb now.

**Comment by Kqliber** [comment]
dont use jcenter, it is deprecated and is to shut down March 31 2022
https://blog.gradle.org/jcenter-shutdown#:~:text=The%20jcenter()%20method%20will,may%20only%20publish%20new%20versions.

**Comment by Kqliber** [comment]
No problem!
