### ISSUE TITLE
Console format needs a channel check per message.

### ISSUE THREAD

**Issue by UPSOKen** [HelpChat/ChatChat#218]
In the console format for ChatChat, if I use %chatchat_channel_name% - it always returns default, unless the person is in the dedicated channel.

I have a staff chat - and you can use **/staff** or use the **@** prefix to send a message.

However, If I use the prefix, the message will successfully go to console and the proper chat in-game, but the %chatchat_channel_name% still returns default channel in console format, rather than staff channel.

I am guessing that means the placeholder returns the active channel the **player** is currently in, and not the channel the particular **message** was sent to. I want the console to log which chat channel each message is sent to, even if the message is sent via a prefix (like **@**) instead of joining the channel (with a command like **/staff**). Is there a built in placeholder like <channel> that can check the channel the message was sent in, rather than the channel the USER who sent the message is currently active in?

**Comment by BlitzOffline** [comment]
Hello,

Your assumptions are pretty spot on. The placeholder shows the current channel the player is in. When we parse any message (channel or prefix channel), we do temporarily change the player's channel but console messages are parsed later after the channel is switched back.

Adding a ChatChat only placeholder won't fix this. I do have a fix in mind however.

I will mark this ticket as an issue and I'll see when I can get work on this done. I'll send the build here when I have one.

**Comment by UPSOKen** [comment]
Sounds good. I wouldn't care that much, but for the channel function, it would be good to have it logged in a way that I can see where people said things. I love using the plugin though :) I'll await a build update!
