### ISSUE TITLE
[Suggestion] Add the ability to put a distance/radius on a chat channel.

### ISSUE THREAD

**Issue by SirKillian** [HelpChat/ChatChat#46]
Add the ability to put a distance/radius on a chat channel.
For example; I'd like to make a "local" chat channel that's only visible to players that are within a X block radius of the sender.

**Comment by Kqliber** [comment]
This has been merged into the master branch now. We will supply a new jar into the discord channel soon enough (whenever, we're ready), or get it from the [actions](https://github.com/HelpChat/ChatChat/actions) page
