### ISSUE TITLE
[Suggestion] Delete Messages

### ISSUE THREAD

**Issue by lucian929** [HelpChat/ChatChat#48]
It'd be a great addition to allow "deleting" messages. From what my friend told me, it works by re-sending all the currently viewable messages in chat minus the deleted one.

**Comment by BlitzOffline** [comment]
Hello. As your friend mentioned there is no way to actually delete messages. Re-sending the messages already sent might work but I can't even think of how it would know what all the sent messages are + this wouldn't even work on clients like Lunar where you have infinite chat. It would just push the message above by x messages. I don't have the final say tho, this is just my opinion. Others might leave their opinion after me in here.

**Comment by BlitzOffline** [comment]
Closing this as we've decided not to add it. Mostly for the reasons listed above. In the future maybe but I wouldn't hold my breath.
