### ISSUE TITLE
[SUGGESTION] Per-player mentions toggle command

### ISSUE THREAD

**Issue by lucian929** [HelpChat/ChatChat#50]
This would be a command like `/mentions toggle` or similar which would allow the player to disable being mentioned. If the player happens to be an admin or streamer, getting frequently mentioned would likely become quite annoying.

**Comment by LagClear** [comment]
I agree with this suggestion great idea!

**Comment by BlitzOffline** [comment]
We are already working on something like this. it will be permission based however. so you can either give permissions to your player and they won't receive pings anymore, or you can make a command to toggle it using plugins like MyCommand
