### ISSUE TITLE
minimessage issues

### ISSUE THREAD

**Issue by LuluxClient** [HelpChat/ChatChat#63]
Mini message is great and all but the fact you can no longer use &f &c etc... it breaks lots of things. For example when creating a rank prefix on luckperms you will only see the good colors in chat but in custom menus and tab and many many many many more plugins that doesn't support minimessage you will only see "<red>MY RANK". Please add support to the old format.

**Comment by BlitzOffline** [comment]
I really don't see how ChatChat is related to other plugins at all? Especially Menu and Tab plugins? If you want to use placeholders from other plugins that don't use MiniMessages in ChatChat you just have to use the Kyorify expansion. We're not adding legacy support. The plan from the start was to have a working replacement for DeluxeChat but not at the cost of improvement. And with the DeluxeChat to ChatChat convertor we've achieved that.

For example on how to use the kyorify expansion: `%luckperms_prefix%` will become `%kyorify_luckperms_prefix%`.
