### ISSUE TITLE
Relational Placeholders

### ISSUE THREAD

**Issue by Funny-cube** [HelpChat/ChatChat#67]
Relational Placeholder support via PAPI is yet to be implemented. Needed for Dchat feature parody.

**Comment by BlitzOffline** [comment]
It is implemented tho. Just for private messages but that's how it works in deluxechat as well

**Comment by PiggyPiglet** [comment]
> It is implemented tho. Just for private messages but that's how it works in deluxechat as well

DeluxeChat has relational placeholder support in regular chat aswell.

**Comment by BlitzOffline** [comment]
> > It is implemented tho. Just for private messages but that's how it works in deluxechat as well
> 
> DeluxeChat has relational placeholder support in regular chat aswell.

Yeah. Me and cube talked about it in discord. I was not aware of that. I always thought its just in private messages. We can do it tho. It will just be a lot more deserializing of messages. I don't know how performance that is.
