### ISSUE TITLE
Ignore Command

### ISSUE THREAD

**Issue by DeOpping** [HelpChat/ChatChat#80]
I'd like to see a /ignore command, just like Essentials.
I'm sure you are already planning on this, but just in case!

**Comment by OneByteGH** [comment]
Id like to add this if I can, my first open source contribution

**Comment by BlitzOffline** [comment]
> Id like to add this if I can, my first open source contribution

PRs are open.

**Comment by Jaimss** [comment]
It's been around a month lol, I can take this if they aren't.

I assume the best way to implement this would be to add a field to ChatUser `Set<UUID> ignoredUsers`
